// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG5eVVB28_nlYl_pyHyyhId36Iwf5vkFw',
    appId: '1:998504400494:web:6447e85420b070585dc87f',
    messagingSenderId: '998504400494',
    projectId: 'fir-testing-ce1e0',
    authDomain: 'fir-testing-ce1e0.firebaseapp.com',
    storageBucket: 'fir-testing-ce1e0.appspot.com',
    measurementId: 'G-L09SECHFQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tCp2uePcdk3WhdT30K2ybj-9WAAPUAk',
    appId: '1:998504400494:android:1c669d38a0a794c75dc87f',
    messagingSenderId: '998504400494',
    projectId: 'fir-testing-ce1e0',
    storageBucket: 'fir-testing-ce1e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfpxlva6vrElrKcbR59dHs3mBoBw-WnVo',
    appId: '1:998504400494:ios:c92ba03a204be5cb5dc87f',
    messagingSenderId: '998504400494',
    projectId: 'fir-testing-ce1e0',
    storageBucket: 'fir-testing-ce1e0.appspot.com',
    iosClientId: '998504400494-qp64qvtj130j7h10enqeth7fvndo04ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTesting',
  );
}
